name: Fast Build for Kibo-RPC

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-levels: 25,26,28
          build-tools: 25.0.3,26.0.2,28.0.3
          ndk: 20.0.5594570
          accept-licenses: true

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kibo-rpc-apk
          path: app/build/outputs/apk/debug/app-debug.apk
