name: Build Kibo-RPC APK

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Java 17 required for sdkmanager in cmdline-tools 16+
      - name: Set up JDK 17 for SDK setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          packages: |
            build-tools;25.0.3
            build-tools;26.0.2
            build-tools;28.0.3
            platforms;android-25
            platforms;android-26
            platforms;android-28
            ndk;20.0.5594570

      # Switch back to Java 8 for your app build
      - name: Set up JDK 8 for Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kibo-rpc-apk
          path: app/build/outputs/apk/debug/app-debug.apk
