name: Build for Kibo-RPC

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install required Android components
        run: |
          sdkmanager \
            "platforms;android-25" \
            "platforms;android-26" \
            "platforms;android-28" \
            "build-tools;25.0.3" \
            "build-tools;26.0.2" \
            "build-tools;28.0.3" \
            "ndk;20.0.5594570"

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kibo-rpc-apk
          path: app/build/outputs/apk/debug/app-debug.apk
